collection=set()
collection.add("rajak")
collection.add("kurnool")
collection.add("hyderabad")
collection.add(1)
collection.add("learning program")
print(collection)
collection.remove(1)
print(collection)